# Generated by Django 6.0 on 2025-12-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('SERIES', 'Series'), ('MOVIE', 'Movie'), ('ANIME', 'Anime'), ('GAME', 'Game')], max_length=10)),
                ('media_title', models.CharField(max_length=255)),
                ('album_title', models.CharField(max_length=255)),
                ('cover_image_url', models.URLField()),
                ('part_or_season', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('artists', models.TextField(help_text='Comma-separated list of artists')),
                ('tracklist', models.TextField(help_text='Each track on a new line')),
                ('total_tracks', models.PositiveIntegerField()),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
