# Generated by Django 6.0 on 2025-12-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frisson_music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
