# Generated by Django 6.0 on 2025-12-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisson_music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='part_or_season',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
