# Generated by Django 6.0 on 2025-12-27 13:00

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frisson_music", "0003_album_release_date_precision_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["media_title"], name="idx_media_title"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["album_title"],
                name="idx_album_title_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["release_date"], name="idx_release_date"
            ),
        ),
    ]
